title: The Vogue Type
description: ""
header_text: ""
footer_text: Copyright 2020 Sabrina Andrade
header_feature_image: ../uploads/text-3-.png
bannerheight: 20vmax
logo: ../uploads/tvt.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
