title: Clothing Brand Typography
description: ""
header_text: ""
footer_text: Copyright 2020 Sabrina Andrade
header_feature_image: ../uploads/bannerimage4.png
bannerheight: 20vmax
logo: ../uploads/logo.png
favicon: ../uploads/logo.png
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About me
    siteurl: /aboutme
