title: Clothing Brand Typography
description: ""
header_text: ""
footer_text: Copyright 2020 Sabrina Andrade
header_feature_image: ../uploads/styletype.png
bannerheight: 20vmax
logo: ../uploads/s.png
favicon: ../uploads/android-chrome-192x192.png
gridlayout: true
fixednavbar: false
upzoom: true
