title: The Vogue Type
description: ""
header_text: ""
footer_text: Copyright 2020 Sabrina Andrade
header_feature_image: ../uploads/text-1-.png
bannerheight: 20vmax
logo: ../uploads/the-vogue-type-1-.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
