title: Brand Clothing Typography
description: ""
header_text: ""
footer_text: Copyright 2020 Sabrina Andrade
header_feature_image: ../uploads/styletype.png
bannerheight: 20vmax
logo: ../uploads/st.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
